### ISSUE TITLE
Can't migrate upstream changes to py-ocd in existing DBs 

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/pupa#284]
Attempting to migrate an existing OCD db fails due to an inconsistent history error:

```bash
> export DJANGO_SETTINGS_MODULE=pupa.settings
> django-admin migrate
Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor.loader.check_consistent_history(connection)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 292, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration pupa.0001_initial is applied before its dependency core.0001_initial on database 'default'.
> django-admin migrate --fake-initial
Traceback (most recent call last):
  File "/home/fgregg/public/opencivicdata/.env/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor.loader.check_consistent_history(connection)
  File "/home/fgregg/public/opencivicdata/.env/lib/python3.5/site-packages/django/db/migrations/loader.py", line 292, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration pupa.0001_initial is applied before its dependency legislative.0001_initial on database 'default'.
```

**Comment by fgregg** [comment]
```sql
>  select * from django_migrations;
 id |      app      |                name                 |            applied   
----+---------------+-------------------------------------+----------------------
 11 | opencivicdata | 0001_initial                        | 2017-03-29 22:40:22.8
 12 | opencivicdata | 0002_add_text                       | 2017-03-29 22:40:24.6
 13 | opencivicdata | 0003_rename_vote_fks                | 2017-03-29 22:40:25.2
 14 | opencivicdata | 0004_auto_20150925_0338             | 2017-03-29 22:40:25.4
 15 | opencivicdata | 0005_add_agenda_item_classification | 2017-03-29 22:40:25.8
 16 | opencivicdata | 0006_auto_20170220_2057             | 2017-03-29 22:40:26.6
 17 | opencivicdata | 0007_auto_20170312_0156             | 2017-03-29 22:40:26.9
 18 | pupa          | 0001_initial                        | 2017-03-29 22:40:28.0
 19 | pupa          | 0002_auto_20150906_1458             | 2017-03-29 22:40:28.4
 20 | pupa          | 0003_auto_20151118_0408             | 2017-03-29 22:40:29.4
(10 rows)
```

**Comment by jamesturk** [comment]
Can you try this:

$ django-admin shell
> DELETE FROM django_migration WHERE app IN ('opencivicdata', 'pupa');
$ django-admin migrate --fake-initial      # will have an error
$ django-admin migrate --fake pupa 0003_auto_20151118_0408

**Comment by jamesturk** [comment]
oops, that should be dbshell on the first line

**Comment by fgregg** [comment]
okay, that worked. (with one more additional django-admin migrate)

**Comment by hancush** [comment]
used this solution w @fgregg's help to resolve this traceback:

```bash
Traceback (most recent call last):
  File "/Users/Hannah/.virtualenvs/ocd/bin/pupa", line 11, in <module>
    load_entry_point('pupa==0.6.0', 'console_scripts', 'pupa')()
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/cli/commands/update.py", line 274, in handle
    return self.do_handle(args, other, juris)
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/cli/commands/update.py", line 319, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/cli/commands/update.py", line 187, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/scrape/base.py", line 102, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/Users/Hannah/hackz/datamade/scrapers-us-municipal/lametro/events.py", line 49, in scrape
    e.pupa_id = str(event['EventId'])
  File "/Users/Hannah/.virtualenvs/ocd/lib/python3.5/site-packages/pupa/scrape/base.py", line 200, in __setattr__
    raise ValueError('property "{}" not in {} schema'.format(key, self._type))
ValueError: property "pupa_id" not in event schema
```

```bash
$ pip install https://github.com/opencivicdata/pupa/zipball/master
$ django-admin dbshell
>>> DELETE FROM django_migrations WHERE app IN ('opencivicdata', 'pupa');
>>> \q
$ django-admin migrate --fake-initial # will have an error
$ django-admin migrate --fake pupa 0003_auto_20151118_0408
```

**Comment by jpmckinney** [comment]
👍 Finally upgraded pupa and needed these steps.
