### ISSUE TITLE
pupa update: scrapelib GET 200 None error

### ISSUE THREAD

**Issue by baisong** [opencivicdata/pupa#302]
Hello, I'm just trying to set up a people scraper for [San Diego City Council](https://www.sandiego.gov/citycouncil) today for the first time following [this guide](http://docs.opencivicdata.org/en/latest/scrape/people.html), using virtualenv and Python 3 on Ubuntu 17.10. [Here's my fork of scrapers-us-municipal](https://github.com/baisong/scrapers-us-municipal). Any tips much appreciated.

#### The issue:

When I run `pupa --loglevel DEBUG update sandiego --scrape` it returns the pasted output below, but I think the error is found in these few lines:

```
15:47:41 INFO scrapelib: GET - https://www.sandiego.gov/citycouncil
15:47:42 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): www.sandiego.gov
15:47:42 DEBUG urllib3.connectionpool: https://www.sandiego.gov:443 "GET /citycouncil HTTP/1.1" 200 None
```

Full output:
```
$ pupa --loglevel DEBUG update sandiego --scrape
no pupa_settings on path, using defaults
sandiego (scrape)
  people: {}
Not checking sessions...
15:47:41 INFO pupa: save jurisdiction City of San Diego as jurisdiction_ocd-jurisdiction-country:us-state:ca-place:san_diego-council_district:1-government.json
15:47:41 DEBUG pupa: {
    "_id": "ocd-jurisdiction/country:us/state:ca/place:san_diego/council_district:1/government",
    "classification": "government",
    "division_id": "ocd-division/country:us/state:ca/place:san_diego/council_district:1",
    "extras": {},
    "feature_flags": [],
    "id": "ocd-jurisdiction/country:us/state:ca/place:san_diego/council_district:1/government",
    "legislative_sessions": [],
    "name": "City of San Diego",
    "url": "http://www.sandiego.gov"
}
15:47:41 INFO pupa: save organization San Diego City Council as organization_38c915d6-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "classification": "legislature",
    "contact_details": [],
    "dissolution_date": "",
    "extras": {},
    "founding_date": "",
    "identifiers": [],
    "image": "",
    "links": [],
    "name": "San Diego City Council",
    "other_names": [],
    "parent_id": null,
    "sources": []
}
15:47:41 INFO pupa: save post Mayor as post_38c915d7-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915d7-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Mayor",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "mayor",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 1 as post_38c915d8-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915d8-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 1",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 2 as post_38c915d9-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915d9-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 2",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 3 as post_38c915da-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915da-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 3",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 4 as post_38c915db-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915db-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 4",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 5 as post_38c915dc-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915dc-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 5",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 6 as post_38c915dd-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915dd-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 6",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 7 as post_38c915de-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915de-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 7",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 8 as post_38c915df-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915df-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 8",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO pupa: save post Councilmember, District 9 as post_38c915e0-f32b-11e7-ab49-f83441dab5bf.json
15:47:41 DEBUG pupa: {
    "_id": "38c915e0-f32b-11e7-ab49-f83441dab5bf",
    "contact_details": [],
    "division_id": null,
    "end_date": "",
    "extras": {},
    "label": "Councilmember, District 9",
    "links": [],
    "organization_id": "38c915d6-f32b-11e7-ab49-f83441dab5bf",
    "role": "councilmember",
    "start_date": ""
}
15:47:41 INFO scrapelib: GET - https://www.sandiego.gov/citycouncil
15:47:42 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): www.sandiego.gov
15:47:42 DEBUG urllib3.connectionpool: https://www.sandiego.gov:443 "GET /citycouncil HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/oren/.virtualenvs/opencivicdataa/bin/pupa", line 11, in <module>
    sys.exit(main())
  File "/home/oren/.virtualenvs/opencivicdataa/lib/python3.6/site-packages/pupa/cli/__main__.py", line 67, in main
    subcommands[args.subcommand].handle(args, other)
  File "/home/oren/.virtualenvs/opencivicdataa/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/home/oren/.virtualenvs/opencivicdataa/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 305, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/home/oren/.virtualenvs/opencivicdataa/lib/python3.6/site-packages/pupa/cli/commands/update.py", line 173, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/home/oren/.virtualenvs/opencivicdataa/lib/python3.6/site-packages/pupa/scrape/base.py", line 108, in do_scrape
    raise ScrapeError('no objects returned from {} scrape'.format(self.__class__.__name__))
pupa.exceptions.ScrapeError: no objects returned from SandiegoPersonScraper scrape
```

**Comment by jamesturk** [comment]
The error indicated suggests that no objects are yielded, can you post a
bit of your code?

**Comment by baisong** [comment]
https://github.com/baisong/scrapers-us-municipal

**Comment by jamesturk** [comment]
I'd check your xpath, at the very least it ends in divdiv which seems wrong

**Comment by baisong** [comment]
Hi @jamesturk, thanks. Yes, I've tried /html/, for example, and it still yields nothing because of the 200 None error. Do you have any ideas of why that might be happening?

**Comment by jamesturk** [comment]
I don't know that's an error, the actual error is the one printed below
about not yielding, are you sure it gets there?

On Jan 10, 2018 12:32, "Oren Robinson" <notifications@github.com> wrote:

Hi @jamesturk <https://github.com/jamesturk>, thanks. Yes, I've tried
/html/, for example, and it still yields nothing because of the 200 None
error. Do you have any ideas of why that might be happening?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opencivicdata/pupa/issues/302#issuecomment-356676402>,
or mute the thread

**Comment by baisong** [comment]
Ah, I guess all of my xpaths have just been wrong. :joy:

Using `"//*[@id=\"block-system-main\"]/div/div[2]/div/main/div/div/div/div/div/div/div"` does seem to match at least one element in the DOM on the [City Council page](https://www.sandiego.gov/citycouncil) (my XPath browser extension shows it matches all nine).

I guess the issue is that none of these XPath subqueries seems to yield the <h2> inside the <div> inside that element...

```
../div/h2
./div/h2
/div/h2
../*/h2
./*/h2
/*/h2
... (many other attempts)
```

They all yield a message like this:
```
name = position.xpath('../div/h2')[0].text
IndexError: list index out of range
```

Thanks again for your help, any more tips much appreciated.

**Comment by jamesturk** [comment]
If you want to experiment w/ the exact DOM you are getting inside the scraper there's a ``scrapeshell`` command you can use like:

``scrapeshell example.com``

at which point you'll be in an IPython session where ``doc`` is the loaded DOM you can query against to narrow down your Xpath

since this doesn't seem to be a pupa problem going to close this one
