### ISSUE TITLE
Relation "opencivicdata_jurisdiction" does not exist

### ISSUE THREAD

**Issue by jmillxyz** [opencivicdata/pupa#316]
Hi,

I'm running 
```$ docker-compose up -d postgres && docker-compose run --rm scrape tx --fastmode```
and get the following error:

```
Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 305, in do_handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 173, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/scrape/base.py", line 111, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 82, in scrape
    for item in analysis_files:
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 54, in _get_ftp_files
    for item in self._get_ftp_files(root, '/'.join([dir_, name])):
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 54, in _get_ftp_files
    for item in self._get_ftp_files(root, '/'.join([dir_, name])):
  File "/opt/openstates/openstates/openstates/tx/bills.py", line 33, in _get_ftp_files
    ftp = ftplib.FTP(root)
  File "/usr/lib/python3.6/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/lib/python3.6/ftplib.py", line 152, in connect
    source_address=self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "opencivicdata_jurisdiction" does not exist
LINE 1: ..., "opencivicdata_jurisdiction"."division_id" FROM "opencivic...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/openstates/venv-pupa//bin/pupa", line 11, in <module>
    load_entry_point('pupa', 'console_scripts', 'pupa')()
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/__main__.py", line 68, in main
    subcommands[args.subcommand].handle(args, other)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 260, in handle
    return self.do_handle(args, other, juris)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 314, in do_handle
    save_report(report, juris.jurisdiction_id)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/openstates/venv-pupa/src/pupa/pupa/cli/commands/update.py", line 76, in save_report
    JurisdictionModel.objects.get(pk=jurisdiction)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/query.py", line 1183, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1061, in execute_sql
    cursor.execute(sql, params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/openstates/venv-pupa/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "opencivicdata_jurisdiction" does not exist
LINE 1: ..., "opencivicdata_jurisdiction"."division_id" FROM "opencivic...
```

Is there a missing table that needs to be added to pupa's migrations?

**Comment by jmillxyz** [comment]
Maybe I need to run pupa dbinit...

**Comment by jmillxyz** [comment]
Yep, covered here: https://github.com/openstates/openstates#getting-started
